# Copyright (C) 2010 Richard Lincoln
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA, USA

pkg_map = {
    "Element": "dynamics",
    "RotatingMachine": "dynamics.iec61970.dynamics",
    "MetaBlockConOutput": "dynamics.iec61970.dynamics",
    "AttributeBlockParameter": "dynamics.iec61970.dynamics",
    "MetaBlock": "dynamics.iec61970.dynamics",
    "BlockParameter": "dynamics.iec61970.dynamics",
    "MetaBlockReference": "dynamics.iec61970.dynamics",
    "ExcitationSystemLimiter": "dynamics.iec61970.dynamics",
    "MetaBlockConnectivity": "dynamics.iec61970.dynamics",
    "ProtectiveDevice": "dynamics.iec61970.dynamics",
    "MetaBlockInput": "dynamics.iec61970.dynamics",
    "SourceModels": "dynamics.iec61970.dynamics",
    "MetaBlockOutputReference": "dynamics.iec61970.dynamics",
    "MetaBlockOutput": "dynamics.iec61970.dynamics",
    "MetaBlockParameter": "dynamics.iec61970.dynamics",
    "BlockConnection": "dynamics.iec61970.dynamics",
    "MetaBlockConInput": "dynamics.iec61970.dynamics",
    "StaticVarDevice": "dynamics.iec61970.dynamics",
    "MetaBlockConnection": "dynamics.iec61970.dynamics",
    "BlockConnectivity": "dynamics.iec61970.dynamics",
    "MetaBlockConSignal": "dynamics.iec61970.dynamics",
    "Block": "dynamics.iec61970.dynamics",
    "MetaBlockStateReference": "dynamics.iec61970.dynamics",
    "AsynchronousMachine": "dynamics.iec61970.dynamics",
    "TieToMeasurement": "dynamics.iec61970.dynamics",
    "MetaBlockSignal": "dynamics.iec61970.dynamics",
    "MetaBlockInputReference": "dynamics.iec61970.dynamics",
    "MetaBlockParameterReference": "dynamics.iec61970.dynamics",
    "MetaBlockConnectable": "dynamics.iec61970.dynamics",
    "MetaBlockState": "dynamics.iec61970.dynamics",
    "LoadStaticSystem": "dynamics.iec61970.dynamics.loads",
    "LoadStaticOwner": "dynamics.iec61970.dynamics.loads",
    "LoadStatic": "dynamics.iec61970.dynamics.loads",
    "AggregateLoad": "dynamics.iec61970.dynamics.loads",
    "LoadMotor": "dynamics.iec61970.dynamics.loads",
    "LoadStaticBus": "dynamics.iec61970.dynamics.loads",
    "LoadStaticZone": "dynamics.iec61970.dynamics.loads",
    "LoadStaticArea": "dynamics.iec61970.dynamics.loads",
    "ExcBAS": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcDC2A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcSEXS": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcELIN2": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC4A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcSK": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC2A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcELIN1": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcST6B": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcST4B": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcWT3E": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcPIC": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcSK2": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcST2A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcHU": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcREXS": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcST7B": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC1A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcDC4B": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcDC1A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC3A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC6A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC5A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcST5B": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcSCRX": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC8B": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcWT2E": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcAC7B": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcWT4E": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcST1A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcBBC": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcitationSystem": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcDC3A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcST3A": "dynamics.iec61970.dynamics.excitation_systems",
    "ExcCZ": "dynamics.iec61970.dynamics.excitation_systems",
    "GovHydro3": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydro2": "dynamics.iec61970.dynamics.turbine_governors",
    "GovGAST": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT1T": "dynamics.iec61970.dynamics.turbine_governors",
    "TurbineGovernor": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT2P": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydroDD": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydroWEH": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT3T": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydroPID": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydro4": "dynamics.iec61970.dynamics.turbine_governors",
    "GovDUM": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydroWPID": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT4P": "dynamics.iec61970.dynamics.turbine_governors",
    "TLCFB1": "dynamics.iec61970.dynamics.turbine_governors",
    "GovGASM": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydroR": "dynamics.iec61970.dynamics.turbine_governors",
    "GovSteamFV2": "dynamics.iec61970.dynamics.turbine_governors",
    "GovRAV": "dynamics.iec61970.dynamics.turbine_governors",
    "GovCT2": "dynamics.iec61970.dynamics.turbine_governors",
    "GovSteam1": "dynamics.iec61970.dynamics.turbine_governors",
    "GovSteamCC": "dynamics.iec61970.dynamics.turbine_governors",
    "GovSteamSGO": "dynamics.iec61970.dynamics.turbine_governors",
    "GovSteamFV3": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT3P": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT1P": "dynamics.iec61970.dynamics.turbine_governors",
    "GovSteam0": "dynamics.iec61970.dynamics.turbine_governors",
    "GovCT1": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT2T": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydro1": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydroPID2": "dynamics.iec61970.dynamics.turbine_governors",
    "GovWT4T": "dynamics.iec61970.dynamics.turbine_governors",
    "GovSteamEU": "dynamics.iec61970.dynamics.turbine_governors",
    "GovHydro0": "dynamics.iec61970.dynamics.turbine_governors",
    "GovGASTWD": "dynamics.iec61970.dynamics.turbine_governors",
    "GovGAST2": "dynamics.iec61970.dynamics.turbine_governors",
    "PowerSystemStabilizer": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssIEEE4B": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssIEEE2B": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssSB4": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssSB": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssSK": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssPTIST3": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssIEEE1A": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssIEEE3B": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssWSCC": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssPTIST1": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "PssSH": "dynamics.iec61970.dynamics.power_system_stabilizers",
    "GenSync": "dynamics.iec61970.dynamics.generators",
    "GenLoad": "dynamics.iec61970.dynamics.generators",
    "GenAsync": "dynamics.iec61970.dynamics.generators",
    "GenEquiv": "dynamics.iec61970.dynamics.generators",
    "VcompIEEE": "dynamics.iec61970.dynamics.voltage_compensator",
    "VoltageCompensator": "dynamics.iec61970.dynamics.voltage_compensator",
    "VcompCross": "dynamics.iec61970.dynamics.voltage_compensator",
    "MotorAsync": "dynamics.iec61970.dynamics.motors",
    "MechanicalLoad": "dynamics.iec61970.dynamics.motors",
    "MechLoad1": "dynamics.iec61970.dynamics.motors",
    "SynchronousMotorType": "dynamics.iec61970.dynamics.motors",
    "MotorSync": "dynamics.iec61970.dynamics.motors",
}
